- hosts: localhost
  connection: local
  gather_facts: False
  vars:
    hostname: Monitoring-Server
    ec2_access_key: "{{ lookup('env', 'ansible_aws_access_key') }}"
    ec2_secret_key: "{{ lookup('env', 'ansible_aws_secret_key') }}"
    instance_type: "t2.micro"
    image: "ami-0badcc5b522737046"
    group: "SSH-HTTP-MONITORING"
    region: "eu-central-1"
  tasks:
    - name: make_one_instance
      ec2: image={{ image }}
           instance_type={{ instance_type }}
           aws_access_key={{ ec2_access_key }}
           aws_secret_key={{ ec2_secret_key }}
           instance_tags='{ "Name":"{{ hostname }}" }'
           region={{ region }}
           group={{ group }}
           wait=true

    - pause:
        minutes: 1

    - name: Gathers facts (instance metadata) about Monitoring-Server
      ec2_instance_facts:
        region: "{{ region }}"
        filters:
          "tag:Name": "{{ hostname }}"
          instance-state-name: running
      register: ec2_instance_facts
    -  set_fact:
         msg: "{{ ec2_instance_facts | json_query('instances[*].public_ip_address') }}"
    - debug: var=msg
