---
# tasks file for deploy_zabbix
- name: Waiting for userdata script
  wait_for:
    path: /var/lib/cloud/instance/boot-finished
    timeout: 1000

- name: Create a directory
  file:
    path: "{{ project_path }}"
    state: directory

- name: Copy zabbix-compose.yml to EC2 instance
  copy:
    src: zabbix-compose.yml
    dest: "{{ project_path }}"

- name: Run zabbix-compose
  become: true
  docker_compose:
    project_src: "{{ project_path }}"
    files: zabbix-compose.yml
  environment:
    MYSQL_USER: "{{ lookup('env', 'MYSQL_USER') }}"
    DB_SERVER_HOST: "{{ lookup('env', 'DB_SERVER_HOST') }}"
    ZBX_JAVAGATEWAY: "{{ lookup('env', 'ZBX_JAVAGATEWAY') }}"
    MYSQL_PASSWORD: "{{ lookup('env', 'MYSQL_PASSWORD') }}"
    MYSQL_ROOT_PASSWORD: "{{ lookup('env', 'MYSQL_ROOT_PASSWORD') }}"
